server:
  port: 8060

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/test;AUTO_SERVER=TRUE
    username: sa
    password: 123456
    schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
  h2:
    console:
      path: /h2-console
      enabled: true
  #Springfox使用的路径匹配是基于AntPathMatcher的
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#MyBatis配置
mybatis:
  type-aliases-package: com.flying.entity #别名定义
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #指定 MyBatis 所用日志的具体实现，未指定时将自动查找
    map-underscore-to-camel-case: true #开启自动驼峰命名规则（camel case）映射
    lazy-loading-enabled: true #开启延时加载开关
    aggressive-lazy-loading: false #将积极加载改为消极加载（即按需加载）,默认值就是false
    lazy-load-trigger-methods: "" #阻挡不相干的操作触发，实现懒加载
    cache-enabled: true #打开全局缓存开关（二级环境），默认值就是true

#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: h2
  reasonable: true
  support-methods-arguments: true